# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Execute Gradle build
      run: chmod +x gradlew
      
    - name: Execute Gradle build
      run: ./gradlew jar
    
    - name: Write changes to repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "upload compiled jar file"
